---
linters:
  disable-all: true
  enable:
    - errcheck
    - goimports
    - govet
    - ineffassign
    - misspell
    - unconvert
    - unused
    - staticcheck
    - nolintlint

linters-settings:
  govet:
    check-shadowing: true
