name: go lint
on:
  workflow_dispatch: {}
  pull_request:
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - "go.work"
      - "go.work.sum"
    branches:
      - main
  push:
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - "go.work"
      - "go.work.sum"
    branches:
      - main

jobs:
  golangci:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.24'
      - uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1.0
          args: --timeout 10m
          github-token: ${{ secrets.github_token }}
