name: test
on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: grip tests
        run: go test ./...
      - name: grip/x tests
        run: |
          retVal=0
          for i in $(find ./x -name "go.mod"); do
              pushd $(dirname $i)
              go test ./...
              if [[ $? ]]; then
                 retVal=1
              fi
              popd
          done
          exit $retVal

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.45.2
